[package]
name = "img_msg_encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.2.1"
clap = { version = "4.5.16", features = ["derive"] }
rand = "0.9.0-alpha.2"